bridge with AAC_tactics through an optional dependency

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8,6 +8,12 @@ while [ "$1" != "" ]; do
 	--disable-ssr)
 	    sed --in-place '/fhrel\.v/d' _CoqProject || echo "warning: sed failed to remove fhrel.v"
 	    ;;
+	--enable-aac)
+	    echo "rewriting_aac.v" >>_CoqProject
+	    ;;
+	--disable-aac)
+	    sed --in-place '/rewriting_aac\.v/d' _CoqProject || echo "warning: sed failed to remove rewriting_aac.v"
+	    ;;
 	*)
 	    echo "unknown option"
 	    ;;
