coq -> rocq

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3,16 +3,16 @@
 while [ "$1" != "" ]; do
     case "$1" in
 	--enable-ssr)
-	    echo "theories/fhrel.v" >>_CoqProject
+	    echo "theories/fhrel.v" >>_RocqProject
 	    ;;
 	--disable-ssr)
-	    sed --in-place '/theories\/fhrel\.v/d' _CoqProject || echo "warning: sed failed to remove fhrel.v"
+	    sed --in-place '/theories\/fhrel\.v/d' _RocqProject || echo "warning: sed failed to remove fhrel.v"
 	    ;;
 	--enable-aac)
-	    echo "theories/rewriting_aac.v" >>_CoqProject
+	    echo "theories/rewriting_aac.v" >>_RocqProject
 	    ;;
 	--disable-aac)
-	    sed --in-place '/theories\/rewriting_aac\.v/d' _CoqProject || echo "warning: sed failed to remove rewriting_aac.v"
+	    sed --in-place '/theories\/rewriting_aac\.v/d' _RocqProject || echo "warning: sed failed to remove rewriting_aac.v"
 	    ;;
 	*)
 	    echo "unknown option"
